// The fabricated starter project migrateFromLegacy() (./project.ts) seeds
// a brand-new browser/install with, when there's no pre-existing
// localStorage data to migrate and nothing synced yet from the Worker.
// Real module-owned export now, moved out of index.html — nothing else
// reads or mutates this (every actual use deep-clones it via
// JSON.parse(JSON.stringify(DEFAULT_JOBS))), so it needs no window
// export.
import type { Job } from '../core/types';

export const DEFAULT_JOBS: Job[] = [
  {
    id: 'job-1',
    name: 'Project Summary 1',
    color: '#6c757d',
    archived: false,
    notes: '',
    tasks: [{ id: 'task-1-1', name: 'Project Summary 1', start: '2026-08-03', finish: '2026-11-06', notes: '', order: 0 }],
  },
  {
    id: 'job-2',
    name: 'Project Summary 2',
    color: '#6c757d',
    archived: false,
    notes: '',
    tasks: [{ id: 'task-2-1', name: 'Project Summary 2', start: '2026-08-03', finish: '2026-11-06', notes: '', order: 0 }],
  },
  {
    id: 'job-3',
    name: 'Initial Setup',
    color: '#9b7edc',
    archived: false,
    notes: 'Foundation and site prep coordination',
    tasks: [{ id: 'task-3-1', name: 'Initial Setup', start: '2026-08-03', finish: '2026-08-07', notes: 'Foundation and site prep coordination', order: 0 }],
  },
  {
    id: 'job-4',
    name: 'Phase 1 Work',
    color: '#6c757d',
    archived: false,
    notes: '',
    tasks: [{ id: 'task-4-1', name: 'Phase 1 Work', start: '2026-08-11', finish: '2026-08-27', notes: '', order: 0 }],
  },
  {
    id: 'job-5',
    name: 'Phase 1 Continuation',
    color: '#6c757d',
    archived: false,
    notes: '',
    tasks: [{ id: 'task-5-1', name: 'Phase 1 Continuation', start: '2026-08-03', finish: '2026-08-27', notes: '', order: 0 }],
  },
  {
    id: 'job-6',
    name: 'Phase 2 Work',
    color: '#6c757d',
    archived: false,
    notes: '',
    tasks: [{ id: 'task-6-1', name: 'Phase 2 Work', start: '2026-08-19', finish: '2026-09-23', notes: '', order: 0 }],
  },
  {
    id: 'job-7',
    name: 'Phase 2A Work',
    color: '#6c757d',
    archived: false,
    notes: '',
    tasks: [{ id: 'task-7-1', name: 'Phase 2A Work', start: '2026-08-31', finish: '2026-09-09', notes: '', order: 0 }],
  },
  {
    id: 'job-8',
    name: 'Phase 2B Work',
    color: '#6c757d',
    archived: false,
    notes: '',
    tasks: [{ id: 'task-8-1', name: 'Phase 2B Work', start: '2026-09-10', finish: '2026-09-23', notes: '', order: 0 }],
  },
  {
    id: 'job-9',
    name: 'Phase 3 Work',
    color: '#6c757d',
    archived: false,
    notes: '',
    tasks: [{ id: 'task-9-1', name: 'Phase 3 Work', start: '2026-09-23', finish: '2026-10-07', notes: '', order: 0 }],
  },
  {
    id: 'job-10',
    name: 'Phase 3A Work',
    color: '#6c757d',
    archived: false,
    notes: '',
    tasks: [{ id: 'task-10-1', name: 'Phase 3A Work', start: '2026-10-07', finish: '2026-10-08', notes: '', order: 0 }],
  },
  {
    id: 'job-11',
    name: 'Phase 4 Work',
    color: '#6c757d',
    archived: false,
    notes: '',
    tasks: [{ id: 'task-11-1', name: 'Phase 4 Work', start: '2026-09-14', finish: '2026-10-15', notes: '', order: 0 }],
  },
  {
    id: 'job-12',
    name: 'Phase 5 Work',
    color: '#6c757d',
    archived: false,
    notes: '',
    tasks: [{ id: 'task-12-1', name: 'Phase 5 Work', start: '2026-09-21', finish: '2026-10-27', notes: '', order: 0 }],
  },
  {
    id: 'job-13',
    name: 'Fire Protection Setup',
    color: '#9b7edc',
    archived: false,
    notes: 'Fire alarm rough-in and testing',
    tasks: [{ id: 'task-13-1', name: 'Fire Protection Setup', start: '2026-10-06', finish: '2026-10-07', notes: 'Fire alarm rough-in and testing', order: 0 }],
  },
  {
    id: 'job-14',
    name: 'Mechanical Rough-in',
    color: '#d4a5d4',
    archived: false,
    notes: 'HVAC ductwork and piping',
    tasks: [{ id: 'task-14-1', name: 'Mechanical Rough-in', start: '2026-09-21', finish: '2026-09-28', notes: 'HVAC ductwork and piping', order: 0 }],
  },
  {
    id: 'job-15',
    name: 'Fire Pro Rough-in',
    color: '#9b7edc',
    archived: false,
    notes: 'Sprinkler line installation',
    tasks: [{ id: 'task-15-1', name: 'Fire Pro Rough-in', start: '2026-09-21', finish: '2026-09-22', notes: 'Sprinkler line installation', order: 0 }],
  },
  {
    id: 'job-16',
    name: 'Electrical Prep',
    color: '#2c3e80',
    archived: false,
    notes: 'Conduit and wire pulls',
    tasks: [{ id: 'task-16-1', name: 'Electrical Prep', start: '2026-09-23', finish: '2026-09-25', notes: 'Conduit and wire pulls', order: 0 }],
  },
  {
    id: 'job-17',
    name: 'Electrical Continuation',
    color: '#2c3e80',
    archived: false,
    notes: 'Panel rough-in',
    tasks: [{ id: 'task-17-1', name: 'Electrical Continuation', start: '2026-09-30', finish: '2026-10-02', notes: 'Panel rough-in', order: 0 }],
  },
  {
    id: 'job-18',
    name: 'Electrical shop area',
    color: '#2c3e80',
    archived: false,
    notes: 'Shop electrical layout and rough',
    tasks: [{ id: 'task-18-1', name: 'Electrical shop area', start: '2026-10-06', finish: '2026-10-13', notes: 'Shop electrical layout and rough', order: 0 }],
  },
  {
    id: 'job-19',
    name: 'Electrical shop area (cont.)',
    color: '#2c3e80',
    archived: false,
    notes: 'Continued shop electrical work',
    tasks: [{ id: 'task-19-1', name: 'Electrical shop area (cont.)', start: '2026-10-14', finish: '2026-10-21', notes: 'Continued shop electrical work', order: 0 }],
  },
  {
    id: 'job-20',
    name: 'Shop lighting, RTUs',
    color: '#2c3e80',
    archived: false,
    notes: 'Light fixture and RTU electrical connections',
    tasks: [{ id: 'task-20-1', name: 'Shop lighting, RTUs', start: '2026-10-22', finish: '2026-10-27', notes: 'Light fixture and RTU electrical connections', order: 0 }],
  },
];
